### ISSUE TITLE
Left align messages across files

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-formatter-pretty#1]
<img width="744" src="https://cloud.githubusercontent.com/assets/170270/14615567/7e9eb39e-05d0-11e6-8459-9ca4b772277c.png">

Right now it looks a bit unaligned. 

The fix is to ensure that the line:col column is the same width in every section.

**Comment by jamestalmage** [comment]
Should we also align the `:` characters?

**Comment by sindresorhus** [comment]
Yes

**Comment by sindresorhus** [comment]
I think the easiest fix would be to treat the filename header and empty lines as messages too. That way we can just have the `text-table` module to all the work for us.
