### ISSUE TITLE
Support string severity

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/eslint-formatter-pretty#14]
I'm not familiar with the output of ESLint, but is it outputting the severity always as a number? Since they dropped support for declaring the severity in the config as a number.

The reason I'm asking is because I'm embedding this awesome formatter in `clinton`. I return my severity as a string (e.g. `warn` and `error`). I can off course iterate over all the messages and translate the severity to it's appropriate number. Just wanted more insights into this first and maybe add support here? Although I would understand that you don't want it because it still is an ESLint formatter.

**Comment by sindresorhus** [comment]
I would be happy to accept a PR adding support for that.
