### ISSUE TITLE
Hide line/column numbers

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/eslint-formatter-pretty#16]
Clinton does not use line/column numbers. It would be nice if I could hide them. There are several implementation methods we could use.

1. Do not show line/column numbers if none of the messages has a `line` or `column` property.
2. Add an options object to explicitly hide that information (not sure on the name of the property yet).

#### 1. Property detection

The benefit with this one is that it doesn't introduce an options object and thus keeping everything simple. The downside is that it might lead to a result you wouldn't expect. Not sure if ESLint always returns line/column numbers.

#### 2. Options object

The downside is that it introduces an extra option (and options object). The benefit is that it is explicit and the user of the formatter can either choose what he wants.

Example: `formatter(result, {showLineNumbers: false})`

**Comment by sindresorhus** [comment]
I would prefer `1`. ESLint always return line:column.
