### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by sholladay** [sindresorhus/eslint-formatter-pretty#26]
I recognize that many people won't necessarily need this, but it would be nice to have an official API documented or at least link to the docs on what ESLint outputs.

I am building a linter and am considering using this as the default reporter. But I hit some snags, probably due to my lack of experience with the ESLint API, which I figured I would share.

Based on a cursory look, I did this just to try it out:

```js
console.log(pretty([
    {
        filePath : 'some-file',
        messages : [
            { severity : 'warn', message : 'foo' }
        ]
    },
    {
        filePath : 'some-other-file',
        messages : [
            { severity : 'warn', message : 'bar', ruleId : 'cool' }
        ]
    }
]));
```

Confusion ensues as there is no output, no error, and the process exits zero. Looking at the source a bit more, I see that I may need to provide `warningCount`, even though this is arguably something that should be calculated automatically for me.

So I go ahead and add `warningCount`, but still nothing happens. Turns out `errorCount` is also required, regardless of what `messages` contains, even if `warningCount` is provided.

At the end of the day, I think this is simply a bug caused by good ol' `NaN` (adding `undefined`). But docs may have been helpful to see a minimum input example.

**Comment by sindresorhus** [comment]
I don't think this is something individual reporters should document. This should be documented in the ESLint project and we can link to it from here. If there are no ESLint docs on this or not good enough, I would suggest opening an issue over there instead.

**Comment by sholladay** [comment]
I see that line of reasoning, though I would argue that a reporter may or may not implement a field that ESLint happens to output. And I think the ESLint folks would say they have no control over what the reporters do.

For posterity: the best docs I could find after-the-fact are for [`executeOnFiles()`](https://eslint.org/docs/developer-guide/nodejs-api#executeonfiles). They don't give any particular indication of why the reporter would not output anything, but at least they document the data structures a bit.
