### ISSUE TITLE
How do you sort things?

### ISSUE THREAD

**Issue by clemtrek** [sindresorhus/eslint-formatter-pretty#30]
I am a beginner(a 15 year old, to be more precise).
Could you please tell me what this line does?

https://github.com/sindresorhus/eslint-formatter-pretty/blob/d686d0736e3b786788889db5939d0830388cbcc6/index.js#L18-L19

**Comment by SamVerschueren** [comment]
These questions are better asked on StackOverflow. See for more info here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort.

In this case, it will sort the result list from least errors to most errors.

**Comment by clemtrek** [comment]
Figured it. Thanks for the link.
