### ISSUE TITLE
chalk.dim is too hard to read on dark backgrounds

### ISSUE THREAD

**Issue by jorgegonzalez** [sindresorhus/eslint-formatter-pretty#31]
Sample XO output in iTerm2 with Snazzy:

![image](https://user-images.githubusercontent.com/12901172/41352770-4b88257a-6ee8-11e8-89e3-acbc77790b57.png)

https://github.com/sindresorhus/eslint-formatter-pretty/blob/master/index.js#L99
https://github.com/sindresorhus/eslint-formatter-pretty/blob/master/index.js#L108
https://github.com/sindresorhus/eslint-formatter-pretty/blob/master/index.js#L110

Can we change these to just `chalk.gray`? The contrast is really bad for dark color themes in my opinion.

**Comment by sindresorhus** [comment]
> https://github.com/sindresorhus/eslint-formatter-pretty/blob/master/index.js#L99

Read the above comment. It's intentionally subtle as it should really have been hidden.

> https://github.com/sindresorhus/eslint-formatter-pretty/blob/master/index.js#L108

This one is just stylistic and it doesn't matter if it's too subtle.

> https://github.com/sindresorhus/eslint-formatter-pretty/blob/master/index.js#L110

I'm fine with changing this one, but maybe we should use only `dim` instead of only `gray`?

**Comment by sindresorhus** [comment]
Why did you close?

**Comment by jorgegonzalez** [comment]
Not sure 🤔
