### ISSUE TITLE
Webpack 4 overlay format

### ISSUE THREAD

**Issue by elawad** [sindresorhus/eslint-formatter-pretty#34]
When using the formatter with Webpack 4 devServer.overlay, output format shows CurrentDir.
 
See the  `]50;CurrentDir=...` in the wepback overlay.

Webpack overlay:
<img width="740" alt="webpack-overlay" src="https://user-images.githubusercontent.com/313249/46750317-ac67ca80-cc85-11e8-8243-fda4fea5f966.png">

Terminal:
<img width="670" alt="terminal" src="https://user-images.githubusercontent.com/313249/46750329-b12c7e80-cc85-11e8-8e25-ea0e71a6bebf.png">

**Comment by sindresorhus** [comment]
Open an issue on Webpack. It's Webpack that is not able to handle the ansi escape code properly.

**Comment by elawad** [comment]
Ok I will check with webpack, thanks.
