### ISSUE TITLE
Support custom ruleUrl

### ISSUE THREAD

**Issue by otakustay** [sindresorhus/eslint-formatter-pretty#45]
Current formatter uses `eslint-rule-docs` to generate a url for each rule id, which supports eslint only

In our project we unified lint on js (eslint), ts (tslint) and css (stylelint), then normalized their output to eslint like and utilized this formatter to output message, however results other than eslint cannot have a correct link on its rule id

It could be very welcome if we can support a `ruleUrl` property for each lint error object

**Comment by sindresorhus** [comment]
Since you're normalizing the output to be ESLint-like, I think #42 will solve your problem.
