### ISSUE TITLE
Not useable from CLI as of version 6

### ISSUE THREAD

**Issue by birtles** [sindresorhus/eslint-formatter-pretty#59]
When specifying a formatter via the CLI, ESLint appears to `require()` the package:

https://github.com/eslint/eslint/blob/c0b11ddb9f8aacc64c3933b9f278939aa7bea481/lib/cli-engine/cli-engine.js#L1048

Since v6, `eslint-formatted-pretty`'s `index.js` is using ESM so it will fail to load when specified from the CLI:

```
❯ yarn eslint --format=pretty
$ /home/me/project/node_modules/.bin/eslint --format=pretty
There was a problem loading formatter: /home/me/project/node_modules/eslint-formatter-pretty/index.js
Error: require() of ES Module /home/me/project/node_modules/eslint-formatter-pretty/index.js from /home/me/project/node_modules/eslint/lib/cli-engine/cli-engine.js not supported.
Instead change the require of index.js in /home/me/project/node_modules/eslint/lib/cli-engine/cli-engine.js to a dynamic import() which is available in all CommonJS modules.
```

Ultimately this should probably be fixed in ESLint (in https://github.com/eslint/eslint/issues/15560 I guess) but for now, perhaps we should remove the part about CLI usage from the README?

**Comment by favna** [comment]
Apologies for reviving a very old issue, but this no longer seems to be the case with ESLint v9.

Linting with this formatter and ESLint v9 gives me:

![image](https://github.com/user-attachments/assets/c6759aa3-64b4-4497-a21c-adcf9e1faa37)

These are my dev deps:

![image](https://github.com/user-attachments/assets/fbd202c7-2775-4b53-99d5-824665f27c02)

I have an `eslint.config.mjs` and I'm running `eslint --fix --format=pretty apps`

**Comment by birtles** [comment]
Seems to work for me too.

**Comment by favna** [comment]
Created a PR to further specify this in the README
