### ISSUE TITLE
Sort by severity first?

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/eslint-formatter-pretty#8]
Sorting by line number makes a lot of sense, but I ignore most warnings anyway (or rather, most warnings I see are ones I evaluated and decided to ignore at some point in the past).

I think it might make sense to put the higher severity `error` at the bottom of the list (since we are scrolling up in our terminal to view it anyways.

Also, it might make sense to reorder the files so those with only warnings and no errors come first. 

This gets that one error you missed down at the bottom of the output every time.

**Comment by sindresorhus** [comment]
> I think it might make sense to put the higher severity error at the bottom of the list (since we are scrolling up in our terminal to view it anyways.

👍 Should still be ordered by line number per warning and error group though.

```
warn 1:4
warn 10:2
error 1:1
error 14:6
```

> Also, it might make sense to reorder the files so those with only warnings and no errors come first.

👍
